# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciaupdate',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existenciaupdate',
            name='capacidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='existenciaupdate',
            name='material_envase',
            field=models.CharField(choices=[('Cristal', 'Cristal'), ('Met\xe1lico', 'Met\xe1lico'), ('Pl\xe1stico', 'Pl\xe1stico'), ('Cart\xf3n', 'Cart\xf3n'), ('Bolsas Multicapa', 'Bolsas Multicapa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='existenciaupdate',
            name='tipo_envase',
            field=models.CharField(blank=True, choices=[('Pomo', 'Pomo'), ('Caja', 'Caja'), ('Tanque', 'Tanque'), ('Lata', 'Lata'), ('Saco', 'Saco')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadupdate',
            name='propiedad',
            field=models.CharField(choices=[('Nocivo', 'Nocivo'), ('Irritante', 'Irritante'), ('Corrosivo', 'Corrosivo'), ('T\xf3xico', 'T\xf3xico'), ('Muy t\xf3xico', 'Muy t\xf3xico'), ('Explosivo', 'Explosivo'), ('Oxidante', 'Oxidante'), ('F\xe1cilmente inflamable', 'F\xe1cilmente inflamable'), ('Extremadamente inflamable', 'Extremadamente inflamable'), ('Peligroso para el medio ambiente', 'Peligroso para el medio ambiente')], max_length=200),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='local',
            field=models.CharField(blank=True, choices=[('Almac\xe9n', 'Almac\xe9n'), ('Ctrl de Calidad/Control de Entrada', 'Ctrl de Calidad/Control de Entrada'), ('Ctrl de Calidad/Control Final', 'Ctrl de Calidad/Control Final'), ('Control de Procesos', 'Control de Procesos'), ('Ctrl de Calidad/Cromatograf\xeda', 'Ctrl de Calidad/Cromatograf\xeda'), ('Ctrl de Calidad/Microbiolog\xeda', 'Ctrl de Calidad/Microbiolog\xeda'), ('Histopatolog\xeda', 'Histopatolog\xeda'), ('Laboratorio de S\xedntesis', 'Laboratorio de S\xedntesis'), ('Microbiolog\xeda', 'Microbiolog\xeda'), ('Parasitolog\xeda de Alcides', 'Parasitolog\xeda de Alcides'), ('Parasitolog\xeda de Serrano', 'Parasitolog\xeda de Serrano'), ('Planta de Tratamiento de Residuales', 'Planta de Tratamiento de Residuales'), ('Protozoolog\xeda', 'Protozoolog\xeda'), ('Toxicolog\xeda', 'Toxicolog\xeda'), ('UMEB', 'UMEB')], default='UMEB', max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='existenciaupdate',
            unique_together=set([('reactivo', 'capacidad', 'unidad_medida', 'tipo_envase', 'material_envase', 'firma')]),
        ),
    ]
