# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0002_auto_20161129_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciaupdate',
            name='cantidad',
            field=models.PositiveIntegerField(error_messages={'requiered': 'Debe insertar un valor para la cantidad de la existencia'}),
        ),
        migrations.AlterField(
            model_name='existenciaupdate',
            name='capacidad',
            field=models.PositiveIntegerField(error_messages={'required': 'Debe insertar un valor para la canacidad de la existencia'}),
        ),
    ]
