# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0004_auto_20161130_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciaupdate',
            name='cantidad',
            field=models.PositiveIntegerField(error_messages={'blank': 'Debe insertar un valor para la cantidad de la existencia'}),
        ),
    ]
