# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0005_auto_20161130_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existenciaupdate',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='existenciaupdate',
            name='capacidad',
            field=models.PositiveIntegerField(),
        ),
    ]
