# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0006_auto_20161130_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactivoupdate',
            name='h_reglas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reactivoupdate',
            name='p_reglas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_cas',
            field=models.CharField(blank=True, help_text='Ejemplo: 234-4-56', max_length=150, null=True, verbose_name='CAS'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_ce',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='CE'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_einecs',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='EINECS'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_icsc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ICSC'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_nu',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='NU'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_rtecs',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='RTECS'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre real'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='nombre_frasco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la etiqueta del frasco'),
        ),
    ]
