# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0007_auto_20161206_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadupdate',
            name='propiedad',
            field=models.CharField(choices=[('Nocivo', 'Nocivo'), ('Irritante', 'Irritante'), ('Corrosivo', 'Corrosivo'), ('T\xf3xico', 'T\xf3xico'), ('Muy t\xf3xico', 'Muy t\xf3xico'), ('Explosivo', 'Explosivo'), ('Oxidante', 'Oxidante'), ('F\xe1cilmente inflamable', 'F\xe1cilmente inflamable'), ('Extremadamente inflamable', 'Extremadamente inflamable'), ('Peligroso para el medio ambiente', 'Peligroso para el medio ambiente'), ('Peligroso para el medio ambiente acu\xe1tico', 'Peligroso para el medio ambiente acu\xe1tico'), ('Narc\xf3tico', 'Narc\xf3tico'), ('Sensibilizante cut\xe1neo', 'Sensibilizante cut\xe1neo'), ('Toxicidad espec\xedfica para un \xf3rgano determinado', 'Toxicidad espec\xedfica para un \xf3rgano determinado'), ('Cancer\xedgeno', 'Cancer\xedgeno'), ('Mutag\xe9nico', 'Mutag\xe9nico'), ('T\xf3xico para la reproducci\xf3n', 'T\xf3xico para la reproducci\xf3n'), ('Sensibilizante respiratorio', 'Sensibilizante respiratorio'), ('Comburente', 'Comburente'), ('Gas a presi\xf3n', 'Gas a presi\xf3n')], max_length=200),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_rtecs',
            field=models.CharField(blank=True, help_text='Ejemplos: AE1225000, I3325000, etc', max_length=150, null=True, verbose_name='RTECS'),
        ),
    ]
