# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compounds_update_app', '0009_auto_20161207_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_cas',
            field=models.CharField(blank=True, help_text='Ejemplos: 19010-66-3, 62-38-4, etc', max_length=150, null=True, verbose_name='CAS'),
        ),
        migrations.AlterField(
            model_name='reactivoupdate',
            name='n_ce',
            field=models.CharField(blank=True, help_text='Ejemplos: 210-817-6, 006-045-00-2, 649-405-00-X etc', max_length=150, null=True, verbose_name='CE'),
        ),
    ]
